# Generated by Django 4.2.1 on 2023-06-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32,null=True)),
                ('image', models.ImageField(upload_to='images/', blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8,default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(max_digits=8, decimal_places=2, default=0)),
                ('description', models.TextField()),
            ],
        ),
    ]
  
