# Generated by Django 3.2.12 on 2023-08-10 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20230805_1012'),
        ('cart', '0004_auto_20230806_0914'),
        ('cart', '0004_auto_20230806_0917'),
    ]

    operations = [
    ]
