# Generated by Django 3.2.12 on 2023-08-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20230805_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'cart'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='totalprice',
            new_name='price',
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default=0, max_length=32),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
