# Generated by Django 3.2.12 on 2023-08-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20230805_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_price',
            new_name='totalprice',
        ),
    ]
