# Generated by Django 3.2.12 on 2023-08-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20230806_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(default=140290254569712, upload_to='images/'),
            preserve_default=False,
        ),
    ]
