# Generated by Django 3.2.12 on 2023-08-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20230805_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
