# Generated by Django 3.2.12 on 2023-08-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
