# Generated by Django 3.2.12 on 2023-08-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='cart_images/'),
        ),
    ]
