# Generated by Django 3.2.12 on 2023-08-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_image'),
        ('cart', '0005_remove_cart_image'),
        ('cart', '0010_alter_cart_image'),
    ]

    operations = [
    ]
