# Generated by Django 3.2.12 on 2023-08-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_name'),
        ('cart', '0005_merge_20230810_0437'),
        ('cart', '0005_rename_total_price_cart_totalprice'),
        ('cart', '0011_merge_20230806_0928'),
    ]

    operations = [
    ]
